require 'fileutils'

# A loose collection of functions and helpers for the Rake files. Also
# includes the hella useful +FileUtils+ library, for which we use
# extensively to simplify shell command calls.
module ActiveCopy
  module Utils
    include FileUtils

    # Tests if the file_path can be destroyed. If it's not generated by
    # this Rake task, it can't be destroyed.
    def destroyable? file_path
      true if file_path != "#{Rails.root}/public"
      true if File.directory? file_path
      true if file_path =~ /index|comments/
      false
    end
  end
end
